kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: testflask
spec:
  template:
    spec:
      containers:
        - name: testflask
          image: image-registry.openshift-image-registry.svc:5000/appdev/testflask:latest