apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-tekton-dashboard-ingress
  namespace: cluster-policies
  annotations:
    apps.open-cluster-management.io/reconcile-option: merge
  generation: 1
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-tekton-dashboard-ingress
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - "*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: extensions/v1beta1
                kind: Ingress
                metadata:
                  name: tekton-dashboard-ingress
                  namespace: tekton-pipelines
                  annotations:
                        kubernetes.io/ingress.class: alb
                        alb.ingress.kubernetes.io/scheme: internet-facing
                        alb.ingress.kubernetes.io/target-type: ip
                spec:
                  rules:
                    - http:
                        paths:
                          - path: /*
                            backend:
                              serviceName: tekton-dashboard
                              servicePort: 9097
          remediationAction: enforce
          severity: high
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-tekton-dashboard-ingress
  namespace: cluster-policies
placementRef:
  name: placementrule-operations-eks
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-tekton-dashboard-ingress
    kind: Policy
    apiGroup: policy.open-cluster-management.io
