commonLabels:
  variant: dev
bases:
  - ../../base
patchesStrategicMerge:
  - placebind-namespace.yaml
  - placebind-sa.yaml
  - placementrule-namespace.yaml
  - placementrule-sa.yaml
  - policy-namespace.yaml
  - policy-namespace.yaml
