apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-sa
spec:
  clusterSelector:
    matchExpressions:
      - {key: env, operator: In, values: ["dev"]}
